WHITESPACE = _{ " " | "\t" | "\n" }
program    = _{ SOI ~ ((assignment | expression) ~ ";"?)* ~ EOI }
assignment =  { variable ~ "=" ~ expression }
// Lambda calculus
expression  = _{ abstraction | application | variable | "(" ~ expression ~ ")" }
abstraction =  { ("\\" | "λ") ~ variable ~ "." ~ expression }
application =  { "(" ~ expression ~ expression ~ ")" }
variable    = @{ ASCII_ALPHANUMERIC+ }
